-- MySQL Script generated by MySQL Workbench
-- Mon Mar 16 09:45:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema struktura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema struktura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `struktura` DEFAULT CHARACTER SET utf8 ;
USE `struktura` ;

-- -----------------------------------------------------
-- Table `struktura`.`pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `struktura`.`pracownicy` (
  `id_pracownika` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  `stanowisko` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pracownika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `struktura`.`pojazdy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `struktura`.`pojazdy` (
  `id_pojazdu` INT NOT NULL AUTO_INCREMENT,
  `marka` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `rejestracja` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pojazdu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `struktura`.`zlecenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `struktura`.`zlecenia` (
  `id_zlecenia` INT NOT NULL AUTO_INCREMENT,
  `adres` VARCHAR(45) NULL,
  `data` DATE NULL,
  `pracownicy_id_pracownika` INT NOT NULL,
  `pojazdy_id_pojazdu` INT NOT NULL,
  PRIMARY KEY (`id_zlecenia`, `pracownicy_id_pracownika`, `pojazdy_id_pojazdu`),
  INDEX `fk_zlecenia_pracownicy_idx` (`pracownicy_id_pracownika` ASC) VISIBLE,
  INDEX `fk_zlecenia_pojazdy1_idx` (`pojazdy_id_pojazdu` ASC) VISIBLE,
  CONSTRAINT `fk_zlecenia_pracownicy`
    FOREIGN KEY (`pracownicy_id_pracownika`)
    REFERENCES `struktura`.`pracownicy` (`id_pracownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zlecenia_pojazdy1`
    FOREIGN KEY (`pojazdy_id_pojazdu`)
    REFERENCES `struktura`.`pojazdy` (`id_pojazdu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `struktura`.`mieszkancy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `struktura`.`mieszkancy` (
  `id_mieszkanca` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  `adres` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  PRIMARY KEY (`id_mieszkanca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `struktura`.`odpady`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `struktura`.`odpady` (
  `id_odpadu` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NULL,
  `typ` VARCHAR(45) NULL,
  `opis` VARCHAR(45) NULL,
  `zlecenia_id_zlecenia` INT NOT NULL,
  PRIMARY KEY (`id_odpadu`, `zlecenia_id_zlecenia`),
  INDEX `fk_odpady_zlecenia1_idx` (`zlecenia_id_zlecenia` ASC) VISIBLE,
  CONSTRAINT `fk_odpady_zlecenia1`
    FOREIGN KEY (`zlecenia_id_zlecenia`)
    REFERENCES `struktura`.`zlecenia` (`id_zlecenia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
